import type { WorkflowState, GitCheckpoint } from '../../state/schemas.js';
import { withAuditEntry } from '../../state/schemas.js';
import type { ActivityDeps } from '../ActivityDeps.js';
import { createLogger } from '../../observability/logger.js';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import * as path from 'node:path';
import * as fs from 'node:fs/promises';

const execFileAsync = promisify(execFile);
const log = createLogger('tacv.git_checkpoint');

/**
 * Git Checkpoint — runs AFTER a successful verifier pass.
 *
 * Creates a git commit on a dedicated branch after each verifier PASS,
 * enabling:
 *   1. True rollback — speculative branches can fork from this commit
 *   2. PR creation at the end of the session
 *   3. Audit history showing exactly what changed at each correction cycle
 *
 * Improvement over TACV original: TACV applied diffs but never committed,
 * so speculative branches started from a dirty working tree. This makes
 * speculative branching semantically correct.
 *
 * Failures are non-fatal — if git is unavailable, we log a warning and
 * continue with a null commitHash.
 */
export async function gitCheckpointImpl(
  state: WorkflowState,
  deps:  ActivityDeps,
): Promise<WorkflowState> {
  const cfg = deps.config.gitCheckpoint;
  if (!cfg.enabled) {
    return state;
  }

  const changedFiles = state.diffProposal?.diffs.map(d => d.filePath) ?? [];
  const branch       = `${cfg.branchPrefix}${state.taskId}`;
  const cycleNumber  = state.correctionCycle.attemptCount;

  log.info('git_checkpoint.start', { branch, files: changedFiles.length, cycle: cycleNumber });

  let commitHash: string | null = null;

  try {
    await runGitArgs(['checkout', '-B', branch], deps.repoPath);
    if (changedFiles.length > 0) {
      await runGitArgs(['add', '--', ...changedFiles], deps.repoPath);
      const msg = `tacv(cycle-${cycleNumber}): ${state.task.description.slice(0, 60)}`;
      await runGitArgs([
        '-c', `user.name=${cfg.authorName}`,
        '-c', `user.email=${cfg.authorEmail}`,
        'commit', '-m', msg, '--allow-empty',
      ], deps.repoPath);
      commitHash = await runGitArgs(['rev-parse', 'HEAD'], deps.repoPath);
    }
    log.info('git_checkpoint.committed', { hash: commitHash, branch });
  } catch (err) {
    log.warn('git_checkpoint.failed', { error: String(err), hint: 'Continuing without git checkpoint' });
  }

  const checkpoint: GitCheckpoint = {
    commitHash,
    branch,
    checkpointAt: Date.now(),
    changedFiles,
    cycleNumber,
  };

  // F1: Generate PR description after a successful commit
  let prDescriptionPath: string | null = null;
  if (commitHash && state.implementationPlan) {
    try {
      prDescriptionPath = await generatePrDescription(state, branch, commitHash, deps.repoPath);
      log.info('git_checkpoint.pr_description_written', { path: prDescriptionPath });
    } catch (err) {
      log.warn('git_checkpoint.pr_description_failed', { error: String(err) });
    }
  }

  return withAuditEntry({
    ...state,
    gitCheckpoint: checkpoint,
  }, {
    node: 'git_checkpoint',
    decision: commitHash ? (prDescriptionPath ? 'committed_with_pr_desc' : 'committed') : 'skipped_git_error',
    keyValues: { commitHash, branch, files: changedFiles.length, prDescriptionPath },
  });
}

async function generatePrDescription(
  state:      WorkflowState,
  branch:     string,
  commitHash: string,
  repoPath:   string,
): Promise<string> {
  const plan = state.implementationPlan!;
  const changedFiles = state.diffProposal?.diffs.map(d => `- \`${d.filePath}\` (${d.operation})`).join('\n') ?? '';

  const lines = [
    `# ${state.task.description}`,
    '',
    '## Summary',
    plan.planSummary,
    '',
    '## Changes',
    changedFiles,
    '',
    '## Testing',
    `- Correction cycles: ${state.correctionCycle.attemptCount}`,
    '- All protection tests: PASS',
    '',
    '## Risky Areas',
    plan.riskyAreas.length > 0
      ? plan.riskyAreas.map(r => `- ${r}`).join('\n')
      : '(none identified)',
    '',
    '---',
    `*Generated by TACV — branch \`${branch}\` — commit \`${commitHash.slice(0, 8)}\`*`,
  ];

  const content = lines.join('\n');
  const prPath = path.join(repoPath, '.workflow', 'pr_description.md');

  await fs.mkdir(path.dirname(prPath), { recursive: true });
  await fs.writeFile(prPath, content);

  return prPath;
}

async function runGitArgs(args: string[], cwd: string): Promise<string> {
  const { stdout } = await execFileAsync('git', args, { cwd });
  return stdout.trim();
}
